export const TOGGLE_SEARCH_BAR = "TOGGLE_SEARCH_BAR";
export const SEARCH_STRING = "SEARCH_STRING";
export const GO_TO_COMPANY_SCREEN = "SEARCH_STRING";

export const STORE_AUTH = "SEARCH_STRING";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const LOAD_COMPANIES = "LOAD_COMPANIES";
export const SEARCH_COMPANY = "SEARCH_COMPANY";
